package com.lessonmaker.app.common.extensionFunctions

import com.lessonmaker.app.extensionFunctions.handleNull
import com.lessonmaker.app.extensionFunctions.removePlus


data class CountryInfo(
    val name: String,
    val code: String,
    val dialCode: String,
    val flag: String,
    val nameAr: String,
    val flagImage: String?=null,
)
val defaultCountry = CountryInfo("United Arab Emirates", "AE", "+971", "🇦🇪", "الإمارات العربية المتحدة")

val countries = listOf(
    CountryInfo("Afghanistan", "AF", "+93", "🇦🇫", "أفغانستان"),
    CountryInfo("Albania", "AL", "+355", "🇦🇱", "ألبانيا"),
    CountryInfo("Algeria", "DZ", "+213", "🇩🇿", "الجزائر"),
    CountryInfo("Andorra", "AD", "+376", "🇦🇩", "أندورا"),
    CountryInfo("Angola", "AO", "+244", "🇦🇴", "أنغولا"),
    CountryInfo("Argentina", "AR", "+54", "🇦🇷", "الأرجنتين"),
    CountryInfo("Armenia", "AM", "+374", "🇦🇲", "أرمينيا"),
    CountryInfo("Australia", "AU", "+61", "🇦🇺", "أستراليا"),
    CountryInfo("Austria", "AT", "+43", "🇦🇹", "النمسا"),
    CountryInfo("Azerbaijan", "AZ", "+994", "🇦🇿", "أذربيجان"),
    CountryInfo("Bahrain", "BH", "+973", "🇧🇭", "البحرين"),
    CountryInfo("Bangladesh", "BD", "+880", "🇧🇩", "بنغلاديش"),
    CountryInfo("Belarus", "BY", "+375", "🇧🇾", "بيلاروسيا"),
    CountryInfo("Belgium", "BE", "+32", "🇧🇪", "بلجيكا"),
    CountryInfo("Belize", "BZ", "+501", "🇧🇿", "بليز"),
    CountryInfo("Benin", "BJ", "+229", "🇧🇯", "بنين"),
    CountryInfo("Bhutan", "BT", "+975", "🇧🇹", "بوتان"),
    CountryInfo("Bolivia", "BO", "+591", "🇧🇴", "بوليفيا"),
    CountryInfo("Bosnia and Herzegovina", "BA", "+387", "🇧🇦", "البوسنة والهرسك"),
    CountryInfo("Botswana", "BW", "+267", "🇧🇼", "بوتسوانا"),
    CountryInfo("Brazil", "BR", "+55", "🇧🇷", "البرازيل"),
    CountryInfo("Brunei", "BN", "+673", "🇧🇳", "بروناي"),
    CountryInfo("Bulgaria", "BG", "+359", "🇧🇬", "بلغاريا"),
    CountryInfo("Burkina Faso", "BF", "+226", "🇧🇫", "بوركينا فاسو"),
    CountryInfo("Burundi", "BI", "+257", "🇧🇮", "بوروندي"),
    CountryInfo("Cambodia", "KH", "+855", "🇰🇭", "كمبوديا"),
    CountryInfo("Cameroon", "CM", "+237", "🇨🇲", "الكاميرون"),
    CountryInfo("Canada", "CA", "+1", "🇨🇦", "كندا"),
    CountryInfo("Chad", "TD", "+235", "🇹🇩", "تشاد"),
    CountryInfo("Chile", "CL", "+56", "🇨🇱", "تشيلي"),
    CountryInfo("China", "CN", "+86", "🇨🇳", "الصين"),
    CountryInfo("Colombia", "CO", "+57", "🇨🇴", "كولومبيا"),
    CountryInfo("Comoros", "KM", "+269", "🇰🇲", "جزر القمر"),
    CountryInfo("Congo - Brazzaville", "CG", "+242", "🇨🇬", "الكونغو - برازافيل"),
    CountryInfo("Congo - Kinshasa", "CD", "+243", "🇨🇩", "الكونغو - كينشاسا"),
    CountryInfo("Costa Rica", "CR", "+506", "🇨🇷", "كوستاريكا"),
    CountryInfo("Croatia", "HR", "+385", "🇭🇷", "كرواتيا"),
    CountryInfo("Cuba", "CU", "+53", "🇨🇺", "كوبا"),
    CountryInfo("Cyprus", "CY", "+357", "🇨🇾", "قبرص"),
    CountryInfo("Czechia", "CZ", "+420", "🇨🇿", "التشيك"),
    CountryInfo("Denmark", "DK", "+45", "🇩🇰", "الدانمارك"),
    CountryInfo("Djibouti", "DJ", "+253", "🇩🇯", "جيبوتي"),
    CountryInfo("Ecuador", "EC", "+593", "🇪🇨", "الإكوادور"),
    CountryInfo("Egypt", "EG", "+20", "🇪🇬", "مصر"),
    CountryInfo("El Salvador", "SV", "+503", "🇸🇻", "السلفادور"),
    CountryInfo("Estonia", "EE", "+372", "🇪🇪", "إستونيا"),
    CountryInfo("Ethiopia", "ET", "+251", "🇪🇹", "إثيوبيا"),
    CountryInfo("Fiji", "FJ", "+679", "🇫🇯", "فيجي"),
    CountryInfo("Finland", "FI", "+358", "🇫🇮", "فنلندا"),
    CountryInfo("France", "FR", "+33", "🇫🇷", "فرنسا"),
    CountryInfo("Gabon", "GA", "+241", "🇬🇦", "الغابون"),
    CountryInfo("Gambia", "GM", "+220", "🇬🇲", "غامبيا"),
    CountryInfo("Georgia", "GE", "+995", "🇬🇪", "جورجيا"),
    CountryInfo("Germany", "DE", "+49", "🇩🇪", "ألمانيا"),
    CountryInfo("Ghana", "GH", "+233", "🇬🇭", "غانا"),
    CountryInfo("Greece", "GR", "+30", "🇬🇷", "اليونان"),
    CountryInfo("Guatemala", "GT", "+502", "🇬🇹", "غواتيمالا"),
    CountryInfo("Honduras", "HN", "+504", "🇭🇳", "هندوراس"),
    CountryInfo("Hungary", "HU", "+36", "🇭🇺", "المجر"),
    CountryInfo("Iceland", "IS", "+354", "🇮🇸", "آيسلندا"),
    CountryInfo("India", "IN", "+91", "🇮🇳", "الهند"),
    CountryInfo("Indonesia", "ID", "+62", "🇮🇩", "إندونيسيا"),
    CountryInfo("Iran", "IR", "+98", "🇮🇷", "إيران"),
    CountryInfo("Iraq", "IQ", "+964", "🇮🇶", "العراق"),
    CountryInfo("Ireland", "IE", "+353", "🇮🇪", "أيرلندا"),
    CountryInfo("Israel", "IL", "+972", "🇮🇱", "إسرائيل"),
    CountryInfo("Italy", "IT", "+39", "🇮🇹", "إيطاليا"),
    CountryInfo("Japan", "JP", "+81", "🇯🇵", "اليابان"),
    CountryInfo("Jordan", "JO", "+962", "🇯🇴", "الأردن"),
    CountryInfo("Kazakhstan", "KZ", "+7", "🇰🇿", "كازاخستان"),
    CountryInfo("Kenya", "KE", "+254", "🇰🇪", "كينيا"),
    CountryInfo("Kuwait", "KW", "+965", "🇰🇼", "الكويت"),
    CountryInfo("Kyrgyzstan", "KG", "+996", "🇰🇬", "قيرغيزستان"),
    CountryInfo("Laos", "LA", "+856", "🇱🇦", "لاوس"),
    CountryInfo("Latvia", "LV", "+371", "🇱🇻", "لاتفيا"),
    CountryInfo("Lebanon", "LB", "+961", "🇱🇧", "لبنان"),
    CountryInfo("Lesotho", "LS", "+266", "🇱🇸", "ليسوتو"),
    CountryInfo("Liberia", "LR", "+231", "🇱🇷", "ليبيريا"),
    CountryInfo("Libya", "LY", "+218", "🇱🇾", "ليبيا"),
    CountryInfo("Lithuania", "LT", "+370", "🇱🇹", "ليتوانيا"),
    CountryInfo("Luxembourg", "LU", "+352", "🇱🇺", "لوكسمبورغ"),
    CountryInfo("Madagascar", "MG", "+261", "🇲🇬", "مدغشقر"),
    CountryInfo("Malawi", "MW", "+265", "🇲🇼", "مالاوي"),
    CountryInfo("Malaysia", "MY", "+60", "🇲🇾", "ماليزيا"),
    CountryInfo("Maldives", "MV", "+960", "🇲🇻", "المالديف"),
    CountryInfo("Mali", "ML", "+223", "🇲🇱", "مالي"),
    CountryInfo("Malta", "MT", "+356", "🇲🇹", "مالطا"),
    CountryInfo("Mauritania", "MR", "+222", "🇲🇷", "موريتانيا"),
    CountryInfo("Mauritius", "MU", "+230", "🇲🇺", "موريشيوس"),
    CountryInfo("Mexico", "MX", "+52", "🇲🇽", "المكسيك"),
    CountryInfo("Moldova", "MD", "+373", "🇲🇩", "مولدوفا"),
    CountryInfo("Monaco", "MC", "+377", "🇲🇨", "موناكو"),
    CountryInfo("Mongolia", "MN", "+976", "🇲🇳", "منغوليا"),
    CountryInfo("Montenegro", "ME", "+382", "🇲🇪", "الجبل الأسود"),
    CountryInfo("Morocco", "MA", "+212", "🇲🇦", "المغرب"),
    CountryInfo("Mozambique", "MZ", "+258", "🇲🇿", "موزمبيق"),
    CountryInfo("Myanmar", "MM", "+95", "🇲🇲", "ميانمار"),
    CountryInfo("Namibia", "NA", "+264", "🇳🇦", "ناميبيا"),
    CountryInfo("Nepal", "NP", "+977", "🇳🇵", "نيبال"),
    CountryInfo("Netherlands", "NL", "+31", "🇳🇱", "هولندا"),
    CountryInfo("New Zealand", "NZ", "+64", "🇳🇿", "نيوزيلندا"),
    CountryInfo("Nicaragua", "NI", "+505", "🇳🇮", "نيكاراغوا"),
    CountryInfo("Nigeria", "NG", "+234", "🇳🇬", "نيجيريا"),
    CountryInfo("North Korea", "KP", "+850", "🇰🇵", "كوريا الشمالية"),
    CountryInfo("Norway", "NO", "+47", "🇳🇴", "النرويج"),
    CountryInfo("Oman", "OM", "+968", "🇴🇲", "عمان"),
    CountryInfo("Pakistan", "PK", "+92", "🇵🇰", "باكستان"),
    CountryInfo("Palestine", "PS", "+970", "🇵🇸", "فلسطين"),
    CountryInfo("Panama", "PA", "+507", "🇵🇦", "بنما"),
    CountryInfo("Papua New Guinea", "PG", "+675", "🇵🇬", "بابوا غينيا الجديدة"),
    CountryInfo("Paraguay", "PY", "+595", "🇵🇾", "باراغواي"),
    CountryInfo("Peru", "PE", "+51", "🇵🇪", "بيرو"),
    CountryInfo("Philippines", "PH", "+63", "🇵🇭", "الفلبين"),
    CountryInfo("Poland", "PL", "+48", "🇵🇱", "بولندا"),
    CountryInfo("Portugal", "PT", "+351", "🇵🇹", "البرتغال"),
    CountryInfo("Qatar", "QA", "+974", "🇶🇦", "قطر"),
    CountryInfo("Romania", "RO", "+40", "🇷🇴", "رومانيا"),
    CountryInfo("Russia", "RU", "+7", "🇷🇺", "روسيا"),
    CountryInfo("Rwanda", "RW", "+250", "🇷🇼", "رواندا"),
    CountryInfo("Samoa", "WS", "+685", "🇼🇸", "ساموا"),
    CountryInfo("San Marino", "SM", "+378", "🇸🇲", "سان مارينو"),
    CountryInfo("São Tomé and Príncipe", "ST", "+239", "🇸🇹", "ساو تومي وبرينسيبي"),
    CountryInfo("Saudi Arabia", "SA", "+966", "🇸🇦", "المملكة العربية السعودية"),
    CountryInfo("Senegal", "SN", "+221", "🇸🇳", "السنغال"),
    CountryInfo("Serbia", "RS", "+381", "🇷🇸", "صربيا"),
    CountryInfo("Seychelles", "SC", "+248", "🇸🇨", "سيشيل"),
    CountryInfo("Sierra Leone", "SL", "+232", "🇸🇱", "سيراليون"),
    CountryInfo("Singapore", "SG", "+65", "🇸🇬", "سنغافورة"),
    CountryInfo("Slovakia", "SK", "+421", "🇸🇰", "سلوفاكيا"),
    CountryInfo("Slovenia", "SI", "+386", "🇸🇮", "سلوفينيا"),
    CountryInfo("Solomon Islands", "SB", "+677", "🇸🇧", "جزر سليمان"),
    CountryInfo("Somalia", "SO", "+252", "🇸🇴", "الصومال"),
    CountryInfo("South Africa", "ZA", "+27", "🇿🇦", "جنوب أفريقيا"),
    CountryInfo("South Korea", "KR", "+82", "🇰🇷", "كوريا الجنوبية"),
    CountryInfo("South Sudan", "SS", "+211", "🇸🇸", "جنوب السودان"),
    CountryInfo("Spain", "ES", "+34", "🇪🇸", "إسبانيا"),
    CountryInfo("Sri Lanka", "LK", "+94", "🇱🇰", "سريلانكا"),
    CountryInfo("Sudan", "SD", "+249", "🇸🇩", "السودان"),
    CountryInfo("Suriname", "SR", "+597", "🇸🇷", "سورينام"),
    CountryInfo("Sweden", "SE", "+46", "🇸🇪", "السويد"),
    CountryInfo("Switzerland", "CH", "+41", "🇨🇭", "سويسرا"),
    CountryInfo("Syria", "SY", "+963", "🇸🇾", "سوريا"),
    CountryInfo("Taiwan", "TW", "+886", "🇹🇼", "تايوان"),
    CountryInfo("Tajikistan", "TJ", "+992", "🇹🇯", "طاجيكستان"),
    CountryInfo("Tanzania", "TZ", "+255", "🇹🇿", "تنزانيا"),
    CountryInfo("Thailand", "TH", "+66", "🇹🇭", "تايلاند"),
    CountryInfo("Timor-Leste", "TL", "+670", "🇹🇱", "تيمور الشرقية"),
    CountryInfo("Togo", "TG", "+228", "🇹🇬", "توغو"),
    CountryInfo("Tonga", "TO", "+676", "🇹🇴", "تونغا"),
    CountryInfo("Tunisia", "TN", "+216", "🇹🇳", "تونس"),
    CountryInfo("Turkey", "TR", "+90", "🇹🇷", "تركيا"),
    CountryInfo("Turkmenistan", "TM", "+993", "🇹🇲", "تركمانستان"),
    CountryInfo("Tuvalu", "TV", "+688", "🇹🇻", "توفالو"),
    CountryInfo("Uganda", "UG", "+256", "🇺🇬", "أوغندا"),
    CountryInfo("Ukraine", "UA", "+380", "🇺🇦", "أوكرانيا"),
    CountryInfo("United Arab Emirates", "AE", "+971", "🇦🇪", "الإمارات العربية المتحدة"),
    CountryInfo("United Kingdom", "GB", "+44", "🇬🇧", "المملكة المتحدة"),
    CountryInfo("United States", "US", "+1", "🇺🇸", "الولايات المتحدة"),
    CountryInfo("Uruguay", "UY", "+598", "🇺🇾", "أوروغواي"),
    CountryInfo("Uzbekistan", "UZ", "+998", "🇺🇿", "أوزبكستان"),
    CountryInfo("Vanuatu", "VU", "+678", "🇻🇺", "فانواتو"),
    CountryInfo("Vatican City", "VA", "+379", "🇻🇦", "الفاتيكان"),
    CountryInfo("Venezuela", "VE", "+58", "🇻🇪", "فنزويلا"),
    CountryInfo("Vietnam", "VN", "+84", "🇻🇳", "فيتنام"),
    CountryInfo("Yemen", "YE", "+967", "🇾🇪", "اليمن"),
    CountryInfo("Zambia", "ZM", "+260", "🇿🇲", "زامبيا"),
    CountryInfo("Zimbabwe", "ZW", "+263", "🇿🇼", "زيمبابوي")

)

fun String.countryFromDialCode():CountryInfo?{
    countries.firstOrNull { it.dialCode.removePlus().equals(this.handleNull().removePlus()) }?.let {
        return it
    }
    return null
}
fun String.countryFromName():CountryInfo?{
    countries.firstOrNull { it.name.equals(this.handleNull()) }?.let {
        return it
    }
    return null
}
data class PhoneNumberFieldOption(
    var dialCode:CountryInfo = defaultCountry,
    var phoneNumber: String
)
